### ISSUE TITLE
rotating package not found

### ISSUE THREAD

**Issue by xmarti6** [metrumresearchgroup/texPreview#15]
Hi, congratulations for this wonderful tool! I've been trying to install it but I came up with this output in windows. I tried with the latest version (1.3.1) and get the same. 

`
> library("texPreview", lib.loc="~/R/win-library/3.5") 
Warning in system(cmd, intern = intern, wait = wait \| intern, show.output.on.console = wait,  :   running command 'C:\WINDOWS\system32\cmd.exe /c mpm --list-package-names \| grep rotating' had status 1 Warning in check_requirments() :   missing tex packages needed for texPreview: rotating 
Warning in system(cmd, intern = intern, wait = wait \| intern, show.output.on.console = wait,  :   running command 'C:\WINDOWS\system32\cmd.exe /c mpm --list-package-names \| grep rotating' had status 1 Warning in check_requirments() :   missing tex packages needed for texPreview: rotating
`

It seems that "rotating" is bundled within the "graphics" package, and is not an independent package anymore. Therefore, "graphics" is listed in "mpm --list-package-names" but not "rotating".  Doesn't look serious, but the warning shows up repeatedly from time to time along the RStudio session.
Thank you very much in advance
Greetings

**Comment by yonicd** [comment]
thanks for bringing this up. i'll update the list that checks for packages.

**Comment by yonicd** [comment]
you can test out the new version from this commit https://github.com/metrumresearchgroup/texPreview/commit/c79d7cb04c759e31c22f08c04b2aa946edf8fd11

**Comment by yonicd** [comment]
patch merged into master https://github.com/metrumresearchgroup/texPreview/commit/dc39feebfb46f2c75db4307a67a419939c835b31

**Comment by xmarti6** [comment]
I'm, indeed, already using the latest version of ImageMagick "2.0". But the "density" parameter worked like a charm, thank you very much!
