### ISSUE TITLE
`usrPackages` not available in `tex_opts`

### ISSUE THREAD

**Issue by andrewheiss** [metrumresearchgroup/texPreview#20]
`tex_opts$set()` allows you to set lots of default options, but `tex_preview()` doesn't read `usrPackages` if it's set in `tex_opts`.

``` r
library(magrittr)
library(texPreview)

# Override the sans serif styling
knitr::kable(head(iris, 5), format = "latex") %>%
  tex_preview(usrPackages = "\\renewcommand*\\familydefault{\\rmdefault}")
```

<img width="628" alt="image" src="https://user-images.githubusercontent.com/73663/59644731-71c70380-912b-11e9-8c53-735627c74bb4.png">

```r
# usrPackages isn't included as one of the options
tex_opts$get()

# Try setting it here
tex_opts$set(
  usrPackages = "\\renewcommand*\\familydefault{\\rmdefault}"  
)

# It doesn't transfer to tex_preview() here
knitr::kable(head(iris, 5), format = "latex") %>%
  tex_preview()
```

<img width="633" alt="image" src="https://user-images.githubusercontent.com/73663/59644752-87d4c400-912b-11e9-9b32-df67fbaba453.png">

**Comment by yonicd** [comment]
Sorry. 

I missed this issue. 

That is right. 

It isn't on the opts list.

You can PR it if you want. I can see how that can be useful.

You can add it here

https://github.com/metrumresearchgroup/texPreview/blob/cb76ab3610c72b3d4c1db3b0c6eef8cdb66dfa88/R/opts.R#L64_L76

**Comment by yonicd** [comment]
added in https://github.com/metrumresearchgroup/texPreview/commit/56d148dc8c27c6022397ef799707cecd71c5dcb4
