### ISSUE TITLE
[Docs] Cannot build pkgdown site

### ISSUE THREAD

**Issue by Blackglade** [metrumresearchgroup/texPreview#22]
I get the following error when trying to build a pkgdown site via `build_site()` with the `rmarkdown.Rmd` vignette:

```
Error : callr subprocess failed: cannot open the connection
Error: callr subprocess failed: callr subprocess failed: cannot open the connection
```

**Comment by yonicd** [comment]
looks like the vignette is depending on slickR, which has been updated on CRAN last week.

https://travis-ci.org/metrumresearchgroup/texPreview/builds/597320175#L7511

**Comment by yonicd** [comment]
this is a travis problem. the magick version is out of synch with the r magic package version

**Comment by yonicd** [comment]
forcing the OS system to be trusty on travis fixes the problem. (this is a known issue) 79a1145

**Comment by yonicd** [comment]
closed: https://github.com/metrumresearchgroup/texPreview/commit/cb76ab3610c72b3d4c1db3b0c6eef8cdb66dfa88
