### ISSUE TITLE
texPreview cannot be installed (Travis)

### ISSUE THREAD

**Issue by bestdan** [metrumresearchgroup/texPreview#34]
`texPreview` is a dependency of a dependency of the [slackr](https://github.com/bestdan/slackr) package. It recently started error'ing on build on Travis: 

https://travis-ci.com/bestdan/slackr

```
* installing *source* package ‘texPreview’ ...
** package ‘texPreview’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
Error : (converted from warning) Rd macro package 'details' is not installed.
ERROR: installing Rd objects failed for package ‘texPreview’
```

Any suggestions for how to fix this? Something in the travis yaml?

**Comment by yonicd** [comment]
Related to Issue https://github.com/metrumresearchgroup/texPreview/issues/31. This will corrected in the upcoming CRAN submission

**Comment by bestdan** [comment]
Thanks, solved!
